import type { Metadata } from "next";
import { Jost } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./admin/_components/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Jost({ subsets: ["latin"] });
const outfit = Outfit({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Home safety cert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
        {children}
        <Toaster/>
        </ThemeProvider>
        </body>
    </html>
  );
}
